# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GF-VUE-ADMIN]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# gorm configuration
gorm:
  config: 'charset=utf8mb4&parseTime=true&loc=Local'
  log-zap: false
  log-mode: "info"
  auto-migrate: true
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 1h
  conn-max-idle-time: 24h
  dsn:
    sources:
      - host: '127.0.0.1'
        port: '13307'
        db-name: 'gin-vue-admin'
        username: 'root'
        password: 'gdkid,,..'
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
    replicas:
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# auto-code configuration
auto-code:
  root: ''
  server:
    api: '/app/api/example'
    boot: '/boot'
    root: ''
    router: '/boot'
    model: '/app/model/example'
    request: '/app/model/example/request'
    service: '/app/service/example'
  web:
    api: '/api'
    root: '/web/src'
    flow: '/view'
    form: '/view'
    table: '/view'
  restart: true